//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilneHotelServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KlientForView", Namespace="http://schemas.datacontract.org/2004/07/MobilneHotel.Models")]
    public partial class KlientForView : object
    {
        
        private string EmailField;
        
        private int IdKlientaField;
        
        private string ImieField;
        
        private string KlientNazwaField;
        
        private string NazwiskoField;
        
        private string TelefonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdKlienta
        {
            get
            {
                return this.IdKlientaField;
            }
            set
            {
                this.IdKlientaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imie
        {
            get
            {
                return this.ImieField;
            }
            set
            {
                this.ImieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KlientNazwa
        {
            get
            {
                return this.KlientNazwaField;
            }
            set
            {
                this.KlientNazwaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwisko
        {
            get
            {
                return this.NazwiskoField;
            }
            set
            {
                this.NazwiskoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon
        {
            get
            {
                return this.TelefonField;
            }
            set
            {
                this.TelefonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PracownikForView", Namespace="http://schemas.datacontract.org/2004/07/MobilneHotelWCF3.ViewModels")]
    public partial class PracownikForView : object
    {
        
        private string EmailField;
        
        private int IdPracownikaField;
        
        private string ImieField;
        
        private string KodPocztowyField;
        
        private string MiastoField;
        
        private string NazwiskoField;
        
        private string NumerDomuField;
        
        private string NumerLokaluField;
        
        private string PeselField;
        
        private string PracownikNazwaField;
        
        private string TelefonField;
        
        private string UlicaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPracownika
        {
            get
            {
                return this.IdPracownikaField;
            }
            set
            {
                this.IdPracownikaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imie
        {
            get
            {
                return this.ImieField;
            }
            set
            {
                this.ImieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodPocztowy
        {
            get
            {
                return this.KodPocztowyField;
            }
            set
            {
                this.KodPocztowyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Miasto
        {
            get
            {
                return this.MiastoField;
            }
            set
            {
                this.MiastoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwisko
        {
            get
            {
                return this.NazwiskoField;
            }
            set
            {
                this.NazwiskoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumerDomu
        {
            get
            {
                return this.NumerDomuField;
            }
            set
            {
                this.NumerDomuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumerLokalu
        {
            get
            {
                return this.NumerLokaluField;
            }
            set
            {
                this.NumerLokaluField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pesel
        {
            get
            {
                return this.PeselField;
            }
            set
            {
                this.PeselField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PracownikNazwa
        {
            get
            {
                return this.PracownikNazwaField;
            }
            set
            {
                this.PracownikNazwaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon
        {
            get
            {
                return this.TelefonField;
            }
            set
            {
                this.TelefonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ulica
        {
            get
            {
                return this.UlicaField;
            }
            set
            {
                this.UlicaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RezerwacjaForView", Namespace="http://schemas.datacontract.org/2004/07/MobilneHotelWCF3.ViewModels")]
    public partial class RezerwacjaForView : object
    {
        
        private System.Nullable<System.DateTime> DataRozpoczeciaField;
        
        private System.Nullable<System.DateTime> DataZakonczeniaField;
        
        private System.Nullable<int> IdKlientaField;
        
        private System.Nullable<int> IdPokojuField;
        
        private System.Nullable<int> IdPracownikaField;
        
        private int IdRezerwacjiField;
        
        private string KlientDaneField;
        
        private string PokojDaneField;
        
        private string PracownikDaneField;
        
        private System.Nullable<decimal> RazemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataRozpoczecia
        {
            get
            {
                return this.DataRozpoczeciaField;
            }
            set
            {
                this.DataRozpoczeciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataZakonczenia
        {
            get
            {
                return this.DataZakonczeniaField;
            }
            set
            {
                this.DataZakonczeniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdKlienta
        {
            get
            {
                return this.IdKlientaField;
            }
            set
            {
                this.IdKlientaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdPokoju
        {
            get
            {
                return this.IdPokojuField;
            }
            set
            {
                this.IdPokojuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdPracownika
        {
            get
            {
                return this.IdPracownikaField;
            }
            set
            {
                this.IdPracownikaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRezerwacji
        {
            get
            {
                return this.IdRezerwacjiField;
            }
            set
            {
                this.IdRezerwacjiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KlientDane
        {
            get
            {
                return this.KlientDaneField;
            }
            set
            {
                this.KlientDaneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PokojDane
        {
            get
            {
                return this.PokojDaneField;
            }
            set
            {
                this.PokojDaneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PracownikDane
        {
            get
            {
                return this.PracownikDaneField;
            }
            set
            {
                this.PracownikDaneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Razem
        {
            get
            {
                return this.RazemField;
            }
            set
            {
                this.RazemField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RodzajPokojuForView", Namespace="http://schemas.datacontract.org/2004/07/MobilneHotelWCF3.ViewModels")]
    public partial class RodzajPokojuForView : object
    {
        
        private int IdRodzajuPokojuField;
        
        private string NazwaField;
        
        private string OpisField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRodzajuPokoju
        {
            get
            {
                return this.IdRodzajuPokojuField;
            }
            set
            {
                this.IdRodzajuPokojuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwa
        {
            get
            {
                return this.NazwaField;
            }
            set
            {
                this.NazwaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opis
        {
            get
            {
                return this.OpisField;
            }
            set
            {
                this.OpisField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PokojForView", Namespace="http://schemas.datacontract.org/2004/07/MobilneHotelWCF3.ViewModels")]
    public partial class PokojForView : object
    {
        
        private System.Nullable<decimal> CenaField;
        
        private int IdPokojuField;
        
        private System.Nullable<int> IdRodzajuPokojuField;
        
        private string NazwaField;
        
        private string NrPokojuField;
        
        private System.Nullable<int> PietroField;
        
        private string RodzajPokojuDaneField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Cena
        {
            get
            {
                return this.CenaField;
            }
            set
            {
                this.CenaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPokoju
        {
            get
            {
                return this.IdPokojuField;
            }
            set
            {
                this.IdPokojuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdRodzajuPokoju
        {
            get
            {
                return this.IdRodzajuPokojuField;
            }
            set
            {
                this.IdRodzajuPokojuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwa
        {
            get
            {
                return this.NazwaField;
            }
            set
            {
                this.NazwaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NrPokoju
        {
            get
            {
                return this.NrPokojuField;
            }
            set
            {
                this.NrPokojuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Pietro
        {
            get
            {
                return this.PietroField;
            }
            set
            {
                this.PietroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RodzajPokojuDane
        {
            get
            {
                return this.RodzajPokojuDaneField;
            }
            set
            {
                this.RodzajPokojuDaneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MobilneHotelServiceReference.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WartoscRezerwacjiKlienta", ReplyAction="http://tempuri.org/IService1/WartoscRezerwacjiKlientaResponse")]
        MobilneHotelServiceReference.WartoscRezerwacjiKlientaResponse WartoscRezerwacjiKlienta(MobilneHotelServiceReference.WartoscRezerwacjiKlientaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WartoscRezerwacjiKlienta", ReplyAction="http://tempuri.org/IService1/WartoscRezerwacjiKlientaResponse")]
        System.Threading.Tasks.Task<MobilneHotelServiceReference.WartoscRezerwacjiKlientaResponse> WartoscRezerwacjiKlientaAsync(MobilneHotelServiceReference.WartoscRezerwacjiKlientaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UtargWDniach", ReplyAction="http://tempuri.org/IService1/UtargWDniachResponse")]
        MobilneHotelServiceReference.UtargWDniachResponse UtargWDniach(MobilneHotelServiceReference.UtargWDniachRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UtargWDniach", ReplyAction="http://tempuri.org/IService1/UtargWDniachResponse")]
        System.Threading.Tasks.Task<MobilneHotelServiceReference.UtargWDniachResponse> UtargWDniachAsync(MobilneHotelServiceReference.UtargWDniachRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllKlienci", ReplyAction="http://tempuri.org/IService1/GetAllKlienciResponse")]
        MobilneHotelServiceReference.GetAllKlienciResponse GetAllKlienci(MobilneHotelServiceReference.GetAllKlienciRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllKlienci", ReplyAction="http://tempuri.org/IService1/GetAllKlienciResponse")]
        System.Threading.Tasks.Task<MobilneHotelServiceReference.GetAllKlienciResponse> GetAllKlienciAsync(MobilneHotelServiceReference.GetAllKlienciRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddModifyKlient", ReplyAction="http://tempuri.org/IService1/AddModifyKlientResponse")]
        MobilneHotelServiceReference.AddModifyKlientResponse AddModifyKlient(MobilneHotelServiceReference.AddModifyKlientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddModifyKlient", ReplyAction="http://tempuri.org/IService1/AddModifyKlientResponse")]
        System.Threading.Tasks.Task<MobilneHotelServiceReference.AddModifyKlientResponse> AddModifyKlientAsync(MobilneHotelServiceReference.AddModifyKlientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteKlient", ReplyAction="http://tempuri.org/IService1/DeleteKlientResponse")]
        MobilneHotelServiceReference.DeleteKlientResponse DeleteKlient(MobilneHotelServiceReference.DeleteKlientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteKlient", ReplyAction="http://tempuri.org/IService1/DeleteKlientResponse")]
        System.Threading.Tasks.Task<MobilneHotelServiceReference.DeleteKlientResponse> DeleteKlientAsync(MobilneHotelServiceReference.DeleteKlientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPracownicy", ReplyAction="http://tempuri.org/IService1/GetAllPracownicyResponse")]
        MobilneHotelServiceReference.GetAllPracownicyResponse GetAllPracownicy(MobilneHotelServiceReference.GetAllPracownicyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPracownicy", ReplyAction="http://tempuri.org/IService1/GetAllPracownicyResponse")]
        System.Threading.Tasks.Task<MobilneHotelServiceReference.GetAllPracownicyResponse> GetAllPracownicyAsync(MobilneHotelServiceReference.GetAllPracownicyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddModifyPracownik", ReplyAction="http://tempuri.org/IService1/AddModifyPracownikResponse")]
        MobilneHotelServiceReference.AddModifyPracownikResponse AddModifyPracownik(MobilneHotelServiceReference.AddModifyPracownikRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddModifyPracownik", ReplyAction="http://tempuri.org/IService1/AddModifyPracownikResponse")]
        System.Threading.Tasks.Task<MobilneHotelServiceReference.AddModifyPracownikResponse> AddModifyPracownikAsync(MobilneHotelServiceReference.AddModifyPracownikRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePracownik", ReplyAction="http://tempuri.org/IService1/DeletePracownikResponse")]
        MobilneHotelServiceReference.DeletePracownikResponse DeletePracownik(MobilneHotelServiceReference.DeletePracownikRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePracownik", ReplyAction="http://tempuri.org/IService1/DeletePracownikResponse")]
        System.Threading.Tasks.Task<MobilneHotelServiceReference.DeletePracownikResponse> DeletePracownikAsync(MobilneHotelServiceReference.DeletePracownikRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllRezerwacje", ReplyAction="http://tempuri.org/IService1/GetAllRezerwacjeResponse")]
        MobilneHotelServiceReference.GetAllRezerwacjeResponse GetAllRezerwacje(MobilneHotelServiceReference.GetAllRezerwacjeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllRezerwacje", ReplyAction="http://tempuri.org/IService1/GetAllRezerwacjeResponse")]
        System.Threading.Tasks.Task<MobilneHotelServiceReference.GetAllRezerwacjeResponse> GetAllRezerwacjeAsync(MobilneHotelServiceReference.GetAllRezerwacjeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddModifyRezerwacja", ReplyAction="http://tempuri.org/IService1/AddModifyRezerwacjaResponse")]
        MobilneHotelServiceReference.AddModifyRezerwacjaResponse AddModifyRezerwacja(MobilneHotelServiceReference.AddModifyRezerwacjaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddModifyRezerwacja", ReplyAction="http://tempuri.org/IService1/AddModifyRezerwacjaResponse")]
        System.Threading.Tasks.Task<MobilneHotelServiceReference.AddModifyRezerwacjaResponse> AddModifyRezerwacjaAsync(MobilneHotelServiceReference.AddModifyRezerwacjaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRezerwacja", ReplyAction="http://tempuri.org/IService1/DeleteRezerwacjaResponse")]
        MobilneHotelServiceReference.DeleteRezerwacjaResponse DeleteRezerwacja(MobilneHotelServiceReference.DeleteRezerwacjaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRezerwacja", ReplyAction="http://tempuri.org/IService1/DeleteRezerwacjaResponse")]
        System.Threading.Tasks.Task<MobilneHotelServiceReference.DeleteRezerwacjaResponse> DeleteRezerwacjaAsync(MobilneHotelServiceReference.DeleteRezerwacjaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllRodzajePokojow", ReplyAction="http://tempuri.org/IService1/GetAllRodzajePokojowResponse")]
        MobilneHotelServiceReference.GetAllRodzajePokojowResponse GetAllRodzajePokojow(MobilneHotelServiceReference.GetAllRodzajePokojowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllRodzajePokojow", ReplyAction="http://tempuri.org/IService1/GetAllRodzajePokojowResponse")]
        System.Threading.Tasks.Task<MobilneHotelServiceReference.GetAllRodzajePokojowResponse> GetAllRodzajePokojowAsync(MobilneHotelServiceReference.GetAllRodzajePokojowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddModifyRodzajPokoju", ReplyAction="http://tempuri.org/IService1/AddModifyRodzajPokojuResponse")]
        MobilneHotelServiceReference.AddModifyRodzajPokojuResponse AddModifyRodzajPokoju(MobilneHotelServiceReference.AddModifyRodzajPokojuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddModifyRodzajPokoju", ReplyAction="http://tempuri.org/IService1/AddModifyRodzajPokojuResponse")]
        System.Threading.Tasks.Task<MobilneHotelServiceReference.AddModifyRodzajPokojuResponse> AddModifyRodzajPokojuAsync(MobilneHotelServiceReference.AddModifyRodzajPokojuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRodzajPokoju", ReplyAction="http://tempuri.org/IService1/DeleteRodzajPokojuResponse")]
        MobilneHotelServiceReference.DeleteRodzajPokojuResponse DeleteRodzajPokoju(MobilneHotelServiceReference.DeleteRodzajPokojuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRodzajPokoju", ReplyAction="http://tempuri.org/IService1/DeleteRodzajPokojuResponse")]
        System.Threading.Tasks.Task<MobilneHotelServiceReference.DeleteRodzajPokojuResponse> DeleteRodzajPokojuAsync(MobilneHotelServiceReference.DeleteRodzajPokojuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPokoje", ReplyAction="http://tempuri.org/IService1/GetAllPokojeResponse")]
        MobilneHotelServiceReference.GetAllPokojeResponse GetAllPokoje(MobilneHotelServiceReference.GetAllPokojeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPokoje", ReplyAction="http://tempuri.org/IService1/GetAllPokojeResponse")]
        System.Threading.Tasks.Task<MobilneHotelServiceReference.GetAllPokojeResponse> GetAllPokojeAsync(MobilneHotelServiceReference.GetAllPokojeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddModifyPokoj", ReplyAction="http://tempuri.org/IService1/AddModifyPokojResponse")]
        MobilneHotelServiceReference.AddModifyPokojResponse AddModifyPokoj(MobilneHotelServiceReference.AddModifyPokojRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddModifyPokoj", ReplyAction="http://tempuri.org/IService1/AddModifyPokojResponse")]
        System.Threading.Tasks.Task<MobilneHotelServiceReference.AddModifyPokojResponse> AddModifyPokojAsync(MobilneHotelServiceReference.AddModifyPokojRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePokoj", ReplyAction="http://tempuri.org/IService1/DeletePokojResponse")]
        MobilneHotelServiceReference.DeletePokojResponse DeletePokoj(MobilneHotelServiceReference.DeletePokojRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePokoj", ReplyAction="http://tempuri.org/IService1/DeletePokojResponse")]
        System.Threading.Tasks.Task<MobilneHotelServiceReference.DeletePokojResponse> DeletePokojAsync(MobilneHotelServiceReference.DeletePokojRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WartoscRezerwacjiKlienta", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class WartoscRezerwacjiKlientaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idKlienta;
        
        public WartoscRezerwacjiKlientaRequest()
        {
        }
        
        public WartoscRezerwacjiKlientaRequest(int idKlienta)
        {
            this.idKlienta = idKlienta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WartoscRezerwacjiKlientaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class WartoscRezerwacjiKlientaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Nullable<decimal> WartoscRezerwacjiKlientaResult;
        
        public WartoscRezerwacjiKlientaResponse()
        {
        }
        
        public WartoscRezerwacjiKlientaResponse(System.Nullable<decimal> WartoscRezerwacjiKlientaResult)
        {
            this.WartoscRezerwacjiKlientaResult = WartoscRezerwacjiKlientaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UtargWDniach", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UtargWDniachRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime odDaty;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime doDaty;
        
        public UtargWDniachRequest()
        {
        }
        
        public UtargWDniachRequest(System.DateTime odDaty, System.DateTime doDaty)
        {
            this.odDaty = odDaty;
            this.doDaty = doDaty;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UtargWDniachResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UtargWDniachResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Nullable<decimal> UtargWDniachResult;
        
        public UtargWDniachResponse()
        {
        }
        
        public UtargWDniachResponse(System.Nullable<decimal> UtargWDniachResult)
        {
            this.UtargWDniachResult = UtargWDniachResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllKlienci", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllKlienciRequest
    {
        
        public GetAllKlienciRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllKlienciResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllKlienciResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<MobilneHotelServiceReference.KlientForView> GetAllKlienciResult;
        
        public GetAllKlienciResponse()
        {
        }
        
        public GetAllKlienciResponse(System.Collections.Generic.List<MobilneHotelServiceReference.KlientForView> GetAllKlienciResult)
        {
            this.GetAllKlienciResult = GetAllKlienciResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddModifyKlient", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddModifyKlientRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MobilneHotelServiceReference.KlientForView klient;
        
        public AddModifyKlientRequest()
        {
        }
        
        public AddModifyKlientRequest(MobilneHotelServiceReference.KlientForView klient)
        {
            this.klient = klient;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddModifyKlientResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddModifyKlientResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddModifyKlientResult;
        
        public AddModifyKlientResponse()
        {
        }
        
        public AddModifyKlientResponse(bool AddModifyKlientResult)
        {
            this.AddModifyKlientResult = AddModifyKlientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteKlient", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteKlientRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int IdKlienta;
        
        public DeleteKlientRequest()
        {
        }
        
        public DeleteKlientRequest(int IdKlienta)
        {
            this.IdKlienta = IdKlienta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteKlientResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteKlientResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DeleteKlientResult;
        
        public DeleteKlientResponse()
        {
        }
        
        public DeleteKlientResponse(bool DeleteKlientResult)
        {
            this.DeleteKlientResult = DeleteKlientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllPracownicy", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllPracownicyRequest
    {
        
        public GetAllPracownicyRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllPracownicyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllPracownicyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<MobilneHotelServiceReference.PracownikForView> GetAllPracownicyResult;
        
        public GetAllPracownicyResponse()
        {
        }
        
        public GetAllPracownicyResponse(System.Collections.Generic.List<MobilneHotelServiceReference.PracownikForView> GetAllPracownicyResult)
        {
            this.GetAllPracownicyResult = GetAllPracownicyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddModifyPracownik", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddModifyPracownikRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MobilneHotelServiceReference.PracownikForView pracownik;
        
        public AddModifyPracownikRequest()
        {
        }
        
        public AddModifyPracownikRequest(MobilneHotelServiceReference.PracownikForView pracownik)
        {
            this.pracownik = pracownik;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddModifyPracownikResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddModifyPracownikResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddModifyPracownikResult;
        
        public AddModifyPracownikResponse()
        {
        }
        
        public AddModifyPracownikResponse(bool AddModifyPracownikResult)
        {
            this.AddModifyPracownikResult = AddModifyPracownikResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeletePracownik", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeletePracownikRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int IdPracownika;
        
        public DeletePracownikRequest()
        {
        }
        
        public DeletePracownikRequest(int IdPracownika)
        {
            this.IdPracownika = IdPracownika;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeletePracownikResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeletePracownikResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DeletePracownikResult;
        
        public DeletePracownikResponse()
        {
        }
        
        public DeletePracownikResponse(bool DeletePracownikResult)
        {
            this.DeletePracownikResult = DeletePracownikResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllRezerwacje", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllRezerwacjeRequest
    {
        
        public GetAllRezerwacjeRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllRezerwacjeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllRezerwacjeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<MobilneHotelServiceReference.RezerwacjaForView> GetAllRezerwacjeResult;
        
        public GetAllRezerwacjeResponse()
        {
        }
        
        public GetAllRezerwacjeResponse(System.Collections.Generic.List<MobilneHotelServiceReference.RezerwacjaForView> GetAllRezerwacjeResult)
        {
            this.GetAllRezerwacjeResult = GetAllRezerwacjeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddModifyRezerwacja", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddModifyRezerwacjaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MobilneHotelServiceReference.RezerwacjaForView rezerwacja;
        
        public AddModifyRezerwacjaRequest()
        {
        }
        
        public AddModifyRezerwacjaRequest(MobilneHotelServiceReference.RezerwacjaForView rezerwacja)
        {
            this.rezerwacja = rezerwacja;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddModifyRezerwacjaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddModifyRezerwacjaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddModifyRezerwacjaResult;
        
        public AddModifyRezerwacjaResponse()
        {
        }
        
        public AddModifyRezerwacjaResponse(bool AddModifyRezerwacjaResult)
        {
            this.AddModifyRezerwacjaResult = AddModifyRezerwacjaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteRezerwacja", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteRezerwacjaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int IdRezerwacji;
        
        public DeleteRezerwacjaRequest()
        {
        }
        
        public DeleteRezerwacjaRequest(int IdRezerwacji)
        {
            this.IdRezerwacji = IdRezerwacji;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteRezerwacjaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteRezerwacjaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DeleteRezerwacjaResult;
        
        public DeleteRezerwacjaResponse()
        {
        }
        
        public DeleteRezerwacjaResponse(bool DeleteRezerwacjaResult)
        {
            this.DeleteRezerwacjaResult = DeleteRezerwacjaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllRodzajePokojow", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllRodzajePokojowRequest
    {
        
        public GetAllRodzajePokojowRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllRodzajePokojowResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllRodzajePokojowResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<MobilneHotelServiceReference.RodzajPokojuForView> GetAllRodzajePokojowResult;
        
        public GetAllRodzajePokojowResponse()
        {
        }
        
        public GetAllRodzajePokojowResponse(System.Collections.Generic.List<MobilneHotelServiceReference.RodzajPokojuForView> GetAllRodzajePokojowResult)
        {
            this.GetAllRodzajePokojowResult = GetAllRodzajePokojowResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddModifyRodzajPokoju", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddModifyRodzajPokojuRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MobilneHotelServiceReference.RodzajPokojuForView rodzajPokoju;
        
        public AddModifyRodzajPokojuRequest()
        {
        }
        
        public AddModifyRodzajPokojuRequest(MobilneHotelServiceReference.RodzajPokojuForView rodzajPokoju)
        {
            this.rodzajPokoju = rodzajPokoju;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddModifyRodzajPokojuResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddModifyRodzajPokojuResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddModifyRodzajPokojuResult;
        
        public AddModifyRodzajPokojuResponse()
        {
        }
        
        public AddModifyRodzajPokojuResponse(bool AddModifyRodzajPokojuResult)
        {
            this.AddModifyRodzajPokojuResult = AddModifyRodzajPokojuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteRodzajPokoju", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteRodzajPokojuRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int IdRodzajPokoju;
        
        public DeleteRodzajPokojuRequest()
        {
        }
        
        public DeleteRodzajPokojuRequest(int IdRodzajPokoju)
        {
            this.IdRodzajPokoju = IdRodzajPokoju;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteRodzajPokojuResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteRodzajPokojuResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DeleteRodzajPokojuResult;
        
        public DeleteRodzajPokojuResponse()
        {
        }
        
        public DeleteRodzajPokojuResponse(bool DeleteRodzajPokojuResult)
        {
            this.DeleteRodzajPokojuResult = DeleteRodzajPokojuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllPokoje", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllPokojeRequest
    {
        
        public GetAllPokojeRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllPokojeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllPokojeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<MobilneHotelServiceReference.PokojForView> GetAllPokojeResult;
        
        public GetAllPokojeResponse()
        {
        }
        
        public GetAllPokojeResponse(System.Collections.Generic.List<MobilneHotelServiceReference.PokojForView> GetAllPokojeResult)
        {
            this.GetAllPokojeResult = GetAllPokojeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddModifyPokoj", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddModifyPokojRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MobilneHotelServiceReference.PokojForView pokoj;
        
        public AddModifyPokojRequest()
        {
        }
        
        public AddModifyPokojRequest(MobilneHotelServiceReference.PokojForView pokoj)
        {
            this.pokoj = pokoj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddModifyPokojResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddModifyPokojResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddModifyPokojResult;
        
        public AddModifyPokojResponse()
        {
        }
        
        public AddModifyPokojResponse(bool AddModifyPokojResult)
        {
            this.AddModifyPokojResult = AddModifyPokojResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeletePokoj", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeletePokojRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int IdPokoju;
        
        public DeletePokojRequest()
        {
        }
        
        public DeletePokojRequest(int IdPokoju)
        {
            this.IdPokoju = IdPokoju;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeletePokojResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeletePokojResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DeletePokojResult;
        
        public DeletePokojResponse()
        {
        }
        
        public DeletePokojResponse(bool DeletePokojResult)
        {
            this.DeletePokojResult = DeletePokojResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface IService1Channel : MobilneHotelServiceReference.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MobilneHotelServiceReference.IService1>, MobilneHotelServiceReference.IService1
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public MobilneHotelServiceReference.WartoscRezerwacjiKlientaResponse WartoscRezerwacjiKlienta(MobilneHotelServiceReference.WartoscRezerwacjiKlientaRequest request)
        {
            return base.Channel.WartoscRezerwacjiKlienta(request);
        }
        
        public System.Threading.Tasks.Task<MobilneHotelServiceReference.WartoscRezerwacjiKlientaResponse> WartoscRezerwacjiKlientaAsync(MobilneHotelServiceReference.WartoscRezerwacjiKlientaRequest request)
        {
            return base.Channel.WartoscRezerwacjiKlientaAsync(request);
        }
        
        public MobilneHotelServiceReference.UtargWDniachResponse UtargWDniach(MobilneHotelServiceReference.UtargWDniachRequest request)
        {
            return base.Channel.UtargWDniach(request);
        }
        
        public System.Threading.Tasks.Task<MobilneHotelServiceReference.UtargWDniachResponse> UtargWDniachAsync(MobilneHotelServiceReference.UtargWDniachRequest request)
        {
            return base.Channel.UtargWDniachAsync(request);
        }
        
        public MobilneHotelServiceReference.GetAllKlienciResponse GetAllKlienci(MobilneHotelServiceReference.GetAllKlienciRequest request)
        {
            return base.Channel.GetAllKlienci(request);
        }
        
        public System.Threading.Tasks.Task<MobilneHotelServiceReference.GetAllKlienciResponse> GetAllKlienciAsync(MobilneHotelServiceReference.GetAllKlienciRequest request)
        {
            return base.Channel.GetAllKlienciAsync(request);
        }
        
        public MobilneHotelServiceReference.AddModifyKlientResponse AddModifyKlient(MobilneHotelServiceReference.AddModifyKlientRequest request)
        {
            return base.Channel.AddModifyKlient(request);
        }
        
        public System.Threading.Tasks.Task<MobilneHotelServiceReference.AddModifyKlientResponse> AddModifyKlientAsync(MobilneHotelServiceReference.AddModifyKlientRequest request)
        {
            return base.Channel.AddModifyKlientAsync(request);
        }
        
        public MobilneHotelServiceReference.DeleteKlientResponse DeleteKlient(MobilneHotelServiceReference.DeleteKlientRequest request)
        {
            return base.Channel.DeleteKlient(request);
        }
        
        public System.Threading.Tasks.Task<MobilneHotelServiceReference.DeleteKlientResponse> DeleteKlientAsync(MobilneHotelServiceReference.DeleteKlientRequest request)
        {
            return base.Channel.DeleteKlientAsync(request);
        }
        
        public MobilneHotelServiceReference.GetAllPracownicyResponse GetAllPracownicy(MobilneHotelServiceReference.GetAllPracownicyRequest request)
        {
            return base.Channel.GetAllPracownicy(request);
        }
        
        public System.Threading.Tasks.Task<MobilneHotelServiceReference.GetAllPracownicyResponse> GetAllPracownicyAsync(MobilneHotelServiceReference.GetAllPracownicyRequest request)
        {
            return base.Channel.GetAllPracownicyAsync(request);
        }
        
        public MobilneHotelServiceReference.AddModifyPracownikResponse AddModifyPracownik(MobilneHotelServiceReference.AddModifyPracownikRequest request)
        {
            return base.Channel.AddModifyPracownik(request);
        }
        
        public System.Threading.Tasks.Task<MobilneHotelServiceReference.AddModifyPracownikResponse> AddModifyPracownikAsync(MobilneHotelServiceReference.AddModifyPracownikRequest request)
        {
            return base.Channel.AddModifyPracownikAsync(request);
        }
        
        public MobilneHotelServiceReference.DeletePracownikResponse DeletePracownik(MobilneHotelServiceReference.DeletePracownikRequest request)
        {
            return base.Channel.DeletePracownik(request);
        }
        
        public System.Threading.Tasks.Task<MobilneHotelServiceReference.DeletePracownikResponse> DeletePracownikAsync(MobilneHotelServiceReference.DeletePracownikRequest request)
        {
            return base.Channel.DeletePracownikAsync(request);
        }
        
        public MobilneHotelServiceReference.GetAllRezerwacjeResponse GetAllRezerwacje(MobilneHotelServiceReference.GetAllRezerwacjeRequest request)
        {
            return base.Channel.GetAllRezerwacje(request);
        }
        
        public System.Threading.Tasks.Task<MobilneHotelServiceReference.GetAllRezerwacjeResponse> GetAllRezerwacjeAsync(MobilneHotelServiceReference.GetAllRezerwacjeRequest request)
        {
            return base.Channel.GetAllRezerwacjeAsync(request);
        }
        
        public MobilneHotelServiceReference.AddModifyRezerwacjaResponse AddModifyRezerwacja(MobilneHotelServiceReference.AddModifyRezerwacjaRequest request)
        {
            return base.Channel.AddModifyRezerwacja(request);
        }
        
        public System.Threading.Tasks.Task<MobilneHotelServiceReference.AddModifyRezerwacjaResponse> AddModifyRezerwacjaAsync(MobilneHotelServiceReference.AddModifyRezerwacjaRequest request)
        {
            return base.Channel.AddModifyRezerwacjaAsync(request);
        }
        
        public MobilneHotelServiceReference.DeleteRezerwacjaResponse DeleteRezerwacja(MobilneHotelServiceReference.DeleteRezerwacjaRequest request)
        {
            return base.Channel.DeleteRezerwacja(request);
        }
        
        public System.Threading.Tasks.Task<MobilneHotelServiceReference.DeleteRezerwacjaResponse> DeleteRezerwacjaAsync(MobilneHotelServiceReference.DeleteRezerwacjaRequest request)
        {
            return base.Channel.DeleteRezerwacjaAsync(request);
        }
        
        public MobilneHotelServiceReference.GetAllRodzajePokojowResponse GetAllRodzajePokojow(MobilneHotelServiceReference.GetAllRodzajePokojowRequest request)
        {
            return base.Channel.GetAllRodzajePokojow(request);
        }
        
        public System.Threading.Tasks.Task<MobilneHotelServiceReference.GetAllRodzajePokojowResponse> GetAllRodzajePokojowAsync(MobilneHotelServiceReference.GetAllRodzajePokojowRequest request)
        {
            return base.Channel.GetAllRodzajePokojowAsync(request);
        }
        
        public MobilneHotelServiceReference.AddModifyRodzajPokojuResponse AddModifyRodzajPokoju(MobilneHotelServiceReference.AddModifyRodzajPokojuRequest request)
        {
            return base.Channel.AddModifyRodzajPokoju(request);
        }
        
        public System.Threading.Tasks.Task<MobilneHotelServiceReference.AddModifyRodzajPokojuResponse> AddModifyRodzajPokojuAsync(MobilneHotelServiceReference.AddModifyRodzajPokojuRequest request)
        {
            return base.Channel.AddModifyRodzajPokojuAsync(request);
        }
        
        public MobilneHotelServiceReference.DeleteRodzajPokojuResponse DeleteRodzajPokoju(MobilneHotelServiceReference.DeleteRodzajPokojuRequest request)
        {
            return base.Channel.DeleteRodzajPokoju(request);
        }
        
        public System.Threading.Tasks.Task<MobilneHotelServiceReference.DeleteRodzajPokojuResponse> DeleteRodzajPokojuAsync(MobilneHotelServiceReference.DeleteRodzajPokojuRequest request)
        {
            return base.Channel.DeleteRodzajPokojuAsync(request);
        }
        
        public MobilneHotelServiceReference.GetAllPokojeResponse GetAllPokoje(MobilneHotelServiceReference.GetAllPokojeRequest request)
        {
            return base.Channel.GetAllPokoje(request);
        }
        
        public System.Threading.Tasks.Task<MobilneHotelServiceReference.GetAllPokojeResponse> GetAllPokojeAsync(MobilneHotelServiceReference.GetAllPokojeRequest request)
        {
            return base.Channel.GetAllPokojeAsync(request);
        }
        
        public MobilneHotelServiceReference.AddModifyPokojResponse AddModifyPokoj(MobilneHotelServiceReference.AddModifyPokojRequest request)
        {
            return base.Channel.AddModifyPokoj(request);
        }
        
        public System.Threading.Tasks.Task<MobilneHotelServiceReference.AddModifyPokojResponse> AddModifyPokojAsync(MobilneHotelServiceReference.AddModifyPokojRequest request)
        {
            return base.Channel.AddModifyPokojAsync(request);
        }
        
        public MobilneHotelServiceReference.DeletePokojResponse DeletePokoj(MobilneHotelServiceReference.DeletePokojRequest request)
        {
            return base.Channel.DeletePokoj(request);
        }
        
        public System.Threading.Tasks.Task<MobilneHotelServiceReference.DeletePokojResponse> DeletePokojAsync(MobilneHotelServiceReference.DeletePokojRequest request)
        {
            return base.Channel.DeletePokojAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:63906/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
