//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilneHotelWCF3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezerwacje
    {
        public int IdRezerwacji { get; set; }
        public Nullable<int> IdKlienta { get; set; }
        public Nullable<int> IdPracownika { get; set; }
        public Nullable<int> IdPokoju { get; set; }
        public Nullable<System.DateTime> DataRozpoczecia { get; set; }
        public Nullable<System.DateTime> DataZakonczenia { get; set; }
        public Nullable<decimal> Razem { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual Pokoje Pokoje { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
    }
}
