//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilneHotelWCF3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RodzajePokojow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RodzajePokojow()
        {
            this.Pokoje = new HashSet<Pokoje>();
        }
    
        public int IdRodzajuPokoju { get; set; }
        public string Nazwa { get; set; }
        public string Opis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pokoje> Pokoje { get; set; }
    }
}
